Fix/keep offset state
okp4/kafka-connector-cosmos pull request #16
Opened 2022-04-07 14:45 UTC by amimart

When handling source records, Kafka Connect dissociate the Producer send and the offset save which can lead to successive `poll` calls without fresh offset value.

Instead of systematically fetch the offset value, we keep its populated state across `poll` calls.

2022-04-07 15:10 UTC, ingvaar submitted a review, later dismissed

2022-04-08 06:36 UTC, ccamel requested changes
Good catch!
Just a suggestion for a minor improvement that I let you consider if useful.

2022-04-08 06:36 UTC, ccamel commented on src/main/kotlin/com/okp4/connect/cosmos/CosmosSourceTask.kt
> +                lastBlockHeightFromOffsetStorage = records[records.size - 1].sourceOffset()[HEIGHT_FIELD] as Long
Could be simplified a bit I guess:

```suggestion
            it.lastOrNull()?.run {
                lastBlockHeightFromOffsetStorage = sourceOffset()[HEIGHT_FIELD] as Long
            }
```

2022-04-08 08:06 UTC, amimart commented on src/main/kotlin/com/okp4/connect/cosmos/CosmosSourceTask.kt
> +                lastBlockHeightFromOffsetStorage = records[records.size - 1].sourceOffset()[HEIGHT_FIELD] as Long
Love it! Thank you 😉

2022-04-08 08:18 UTC, ccamel approved these changes

2022-04-08 08:19 UTC, ingvaar approved these changes

2022-04-08 08:29 UTC, merged